export const INTROSPECTION_INIT = 'INTROSPECTION_INIT'
export const INTROSPECTION_TYPE = 'INTROSPECTION_TYPE'
export const INTROSPECTION_TYPE_OK = 'INTROSPECTION_TYPE_OK'
export const INTROSPECTION_TYPE_FAIL = 'INTROSPECTION_TYPE_FAIL'
