const types = {
  INTROSPECTION_INIT: 'INTROSPECTION_INIT',
  INTROSPECTION_TYPE: 'INTROSPECTION_TYPE',
  INTROSPECTION_TYPE_OK: 'INTROSPECTION_TYPE_OK',
  INTROSPECTION_TYPE_FAIL: 'INTROSPECTION_TYPE_FAIL',
}

export default types
